name: Test systemd Docker Images
on:
  workflow_call:

jobs:
  cgroup-v1:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [ -z $(jq -r .baseos.digest baseos_digest) ]; \
          then echo "BASEOS_DIGEST=""" >> $GITHUB_ENV; \
          else echo "BASEOS_DIGEST="@$(jq -r .baseos.digest baseos_digest)"" >> $GITHUB_ENV; \
          fi

      - name: Build a test image
        run: |
          docker build --build-arg BASEOS_DIGEST=${{ env.BASEOS_DIGEST }} --tag test-image .

      - name: Create a test container
        run: >-
          docker run --name test-container --detach --privileged
          --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
          --tmpfs /run --tmpfs /tmp
          --cgroupns host
          test-image

      - name: Check if container is running
        run: timeout 60s bash -c 'until [ "$(docker inspect -f {{.State.Running}} test-container)" == "true" ]; do sleep 2; done'

      - name: Test systemctl
        run: docker exec --tty test-container env TERM=xterm systemctl --version

  cgroup-v2:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [ -z $(jq -r .baseos.digest baseos_digest) ]; \
          then echo "BASEOS_DIGEST=""" >> $GITHUB_ENV; \
          else echo "BASEOS_DIGEST="@$(jq -r .baseos.digest baseos_digest)"" >> $GITHUB_ENV; \
          fi

      - name: Build a test image
        run: |
          docker build --build-arg BASEOS_DIGEST=${{ env.BASEOS_DIGEST }} --tag test-image .

      - name: Create a test container
        run: >-
          docker run --name test-container --detach --privileged
          --volume /sys/fs/cgroup:/sys/fs/cgroup:rw
          --tmpfs /run --tmpfs /tmp
          --cgroupns host
          test-image

      - name: Check if container is running
        run: timeout 20s bash -c 'until [ "$(docker inspect -f {{.State.Running}} test-container)" == "true" ]; do sleep 2; done'

      - name: Test systemctl
        run: docker exec --tty test-container env TERM=xterm systemctl --version

  check:
    if: ${{ always() }}
    needs:
      - cgroup-v1
      - cgroup-v2
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.cgroup-v1.result }}',
          '${{ needs.cgroup-v2.result }}'
          ]) == {'success'}"
